version: "2"
services:
  hub:
    image: selenium/hub:2.53.0
    ports:
      - "4444:4444"
    volumes:
      - "/dev/urandom:/dev/random"
  chrome:
    #image: selenium/node-chrome-debug:2.53.0
    #ports: [ "5900" ]
    build: chrome
    environment:
      - HUB_PORT_4444_TCP_ADDR=hub
      - HUB_PORT_4444_TCP_PORT=4444
    depends_on:
      - hub
    tmpfs:
      - /tmp
  firefox:
    #image: selenium/node-firefox-debug:2.53.0
    #ports: [ "5900" ]
    build: firefox
    environment:
      - HUB_PORT_4444_TCP_ADDR=hub
      - HUB_PORT_4444_TCP_PORT=4444
    depends_on:
      - hub
    tmpfs:
      - /tmp
