version: '2'
services:
  hub:
    image: selenium/hub
    ports:
      - "4444:4444"
  chrome:
    build: chrome
    environment:
      - HUB_PORT_4444_TCP_ADDR=hub
      - HUB_PORT_4444_TCP_PORT=4444
    links:
      - hub
  firefox:
    build: firefox
    environment:
      - HUB_PORT_4444_TCP_ADDR=hub
      - HUB_PORT_4444_TCP_PORT=4444
    links:
      - hub

