version: "2"
services:
  hub:
    image: selenium/hub:2.53.0
    ports:
      - "4444:4444"
  chrome:
    image: harreorz/node-chrome-ja:2.53.0
    environment:
      - HUB_PORT_4444_TCP_ADDR=hub
      - HUB_PORT_4444_TCP_PORT=4444
    depends_on:
      - hub
    tmpfs:
      - /tmp
  chrome-debug:
    image: harreorz/node-chrome-debug-ja:2.53.0
    environment:
      - HUB_PORT_4444_TCP_ADDR=hub
      - HUB_PORT_4444_TCP_PORT=4444
    depends_on:
      - hub
    tmpfs:
      - /tmp
  firefox:
    image: harreorz/node-chrome-ja:2.53.0
    environment:
      - HUB_PORT_4444_TCP_ADDR=hub
      - HUB_PORT_4444_TCP_PORT=4444
    depends_on:
      - hub
    tmpfs:
      - /tmp
  firefox-debug:
    image: harreorz/node-firefox-debug-ja:2.53.0
    environment:
      - HUB_PORT_4444_TCP_ADDR=hub
      - HUB_PORT_4444_TCP_PORT=4444
    depends_on:
      - hub
    tmpfs:
      - /tmp
