version: "2"
services:
  hub:
    image: selenium/hub:3.2.0
    ports:
      - "4444:4444"
  chrome:
#    image: selenium/node-chrome:3.2.0
    build: chrome
    environment:
      - HUB_PORT_4444_TCP_ADDR=hub
      - HUB_PORT_4444_TCP_PORT=4444
    links:
      - hub
  chrome-debug:
#    image: selenium/node-chrome-debug:3.2.0
    build: chrome-debug
    environment:
      - HUB_PORT_4444_TCP_ADDR=hub
      - HUB_PORT_4444_TCP_PORT=4444
    links:
      - hub
  firefox:
#    image: selenium/node-firefox:3.2.0
    build: firefox
    environment:
      - HUB_PORT_4444_TCP_ADDR=hub
      - HUB_PORT_4444_TCP_PORT=4444
    links:
      - hub
  firefox-debug:
#    image: selenium/node-chrome-debug:3.2.0
    build: firefox-debug
    environment:
      - HUB_PORT_4444_TCP_ADDR=hub
      - HUB_PORT_4444_TCP_PORT=4444
    links:
      - hub

